name: OpenTofu CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    uses: openjusticeok/actions/.github/workflows/tofu-ci.yml@main
    with:
      tofu_version: 1.8.1
      directories: |
        [
          "modules/gcp/project-factory",
          "modules/gcp/environment-factory",
          "examples/gcp/project-factory-example",
          "examples/gcp/environment-factory-example"
        ]